### PR TITLE
Example

### PR DESCRIPTION
**Pull request by rantoine**
After stumbling across your blog post I spent some time playing with psm and in the process of doing so decided to build an example with a little complexity to better demonstrate the usefulness of psm. Let me know your thoughts.

### CODE REVIEW

**Comment by corysimmons** [comment]
Thanks @rantoine 

I appreciate it but it's a bit messy. Care if I close this and just add a similar, slightly cleaned-up, example to the README?

I'm glad PSM is proving useful for you. I've personally been finding it a bit cumbersome for small projects, but I think on medium-to-large projects the variables alone would be really helpful.

I'm also starting to wonder if `psm:watch` should depend on Nodemon somehow to just keep it from needing to be started/stopped. Thoughts?

**Comment by rantoine** [comment]
No worries at all. This was a quick hack that I was playing with and simply wanted to run the idea past you. 
I do like the idea of making use of nodemon.

**Comment by corysimmons** [comment]
I'll tinker around with the nodemon thing tonight and see how it feels, then I'll create a more complex/working example.

Thanks for trying out PSM. I'm never sure how useful these tools to other people until someone speaks up. 😻

**Comment by rantoine** [comment]
I've been playing around with moving away from Grunt and/or Gulp to use pure NPM or something pretty close to it. As a result of doing some reading I stumbled across psm. 
Let me know what you how your 'tinking' turns out.

**Comment by corysimmons** [comment]
Okay, I think the best setup is PSM + Rollup or Webpack 2 (exclusively for JS bundles), but feel free to do your own research.

**Comment by rantoine** [comment]
Too funny. 
I was just reading up on Rollup earlier this morning and very much like what I was finding. Now with that stated, it looks like the differences are pretty minor between Webpack 2 and Rollup. Thanks for the note.

**Pull request closed without merging**
